package vistagraficaqytetet;

import controladorqytetet.ControladorQytetet;

public class VistaGraficaQytetet extends javax.swing.JFrame {
    int operacionElegida;
    private ControladorQytetet controlador = ControladorQytetet.getInstance();
    private modeloqytetet.Qytetet modelo = modeloqytetet.Qytetet.getInstance();
    
    public VistaGraficaQytetet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMensajes = new javax.swing.JScrollPane();
        areaMensajes = new java.awt.TextArea();
        panelJugadorActual = new javax.swing.JScrollPane();
        areaJugadorActual = new java.awt.TextArea();
        panelCartaActual = new javax.swing.JScrollPane();
        areaCartaActual = new java.awt.TextArea();
        panelTablero = new javax.swing.JScrollPane();
        areaTablero = new java.awt.TextArea();
        panelJugadores = new javax.swing.JScrollPane();
        areaJugadores = new java.awt.TextArea();
        barraMenu = new javax.swing.JMenuBar();
        jMenuOperacion = new javax.swing.JMenu();
        jMenuCasilla = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMensajes.setViewportView(areaMensajes);

        panelJugadorActual.setViewportView(areaJugadorActual);

        panelCartaActual.setViewportView(areaCartaActual);

        panelTablero.setViewportView(areaTablero);

        panelJugadores.setViewportView(areaJugadores);

        jMenuOperacion.setText("Operacion");
        barraMenu.add(jMenuOperacion);

        jMenuCasilla.setText("Casilla");
        barraMenu.add(jMenuCasilla);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMensajes, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelJugadorActual, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCartaActual, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelJugadores, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelJugadorActual)
                    .addComponent(panelMensajes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
                    .addComponent(panelCartaActual, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelTablero, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelJugadores))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGraficaQytetet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGraficaQytetet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGraficaQytetet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGraficaQytetet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGraficaQytetet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea areaCartaActual;
    private java.awt.TextArea areaJugadorActual;
    private java.awt.TextArea areaJugadores;
    private java.awt.TextArea areaMensajes;
    private java.awt.TextArea areaTablero;
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu jMenuCasilla;
    private javax.swing.JMenu jMenuOperacion;
    private javax.swing.JScrollPane panelCartaActual;
    private javax.swing.JScrollPane panelJugadorActual;
    private javax.swing.JScrollPane panelJugadores;
    private javax.swing.JScrollPane panelMensajes;
    private javax.swing.JScrollPane panelTablero;
    // End of variables declaration//GEN-END:variables
}
