package modeloqytetet;

/**
 *
 * @author root
 */
public enum EstadoJuego {
    JA_CONSORPRESA, ALGUNJUGADORENBANCARROTA, JA_PUEDECOMPRARGESTIONAR, JA_PUEDEGESTIONAR, JA_PREPARADO, JA_ENCARCELADO, JA_ENCARCELADOCONOPCIONDELIBERTAD
}
